webtalk_init -webtalk_dir D:/Data/VHDLprojects2020/VGAframeBuffer/VGAframeBuffer.sim/sim_1/behav/xsim/xsim.dir/TB_VGASync_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 13 00:09:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ac6f6af-bd17-4d0d-8798-9a63b40a5747" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1f43f833b0114abb8877e53db4a551e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11367625971 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "136.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "24788_KB" -context "xsim\\usage"
webtalk_transmit -clientid 803801378 -regid "" -xml D:/Data/VHDLprojects2020/VGAframeBuffer/VGAframeBuffer.sim/sim_1/behav/xsim/xsim.dir/TB_VGASync_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Data/VHDLprojects2020/VGAframeBuffer/VGAframeBuffer.sim/sim_1/behav/xsim/xsim.dir/TB_VGASync_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Data/VHDLprojects2020/VGAframeBuffer/VGAframeBuffer.sim/sim_1/behav/xsim/xsim.dir/TB_VGASync_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
